version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "4000:80"
    depends_on:
      - rest-api
    networks:
      - app-network

  rest-api:
    build: ./rest-api
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=inventory_db
    networks:
      - app-network

  database:
    build: ./database
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=inventory_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge